package lovr.graphics;

@:native("lovr.graphics.Pass")
extern class Pass {
  public function beginTally():Float;
  public function box(?x:Float):Void;
  public function capsule(?x:Float):Void;
  public function circle(?x:Float):Void;
  public function compute(?x:Float):Void;
  public function cone(?x:Float):Void;
  public function cube(?x:Float):Void;
  public function cylinder(?x:Float):Void;
  public function finishTally():Float;
  public function getCanvas():Dynamic;
  public function getClear():Dynamic;
  public function getDimensions():Float;
  public function getHeight():Float;
  public function getLabel():String;
  public function getProjection():Float;
  public function getStats():Float;
  public function getTallyBuffer():lovr.graphics.Buffer;
  public function getViewCount():Float;
  public function getViewPose():Float;
  public function getWidth():Float;
  public function mesh(vertices:lovr.graphics.Buffer):Void;
  public function plane(?x:Float):Void;
  public function roundrect(?x:Float):Void;
  public function setDepthOffset(?offset:Float):Void;
  public function sphere(?x:Float):Void;
  public function torus(?x:Float):Void;
  public function translate(x:Float, y:Float, z:Float):Void;
  public function rotate(angle:Float, ax:Float, ay:Float, az:Float):Void;
  public function scale(x:Float, y:Float, z:Float):Void;
  public function transform(matrix:Array<Float>):Void;
  public function origin():Void;
  public function push():Void;
  public function pop():Void;
  public function line(x1:Float, y1:Float, z1:Float, x2:Float, y2:Float, z2:Float):Void;
  public function points(points:Array<Float>):Void;
  public function polygon(points:Array<Float>):Void;
  public function setColor(r:Float, g:Float, b:Float, ?a:Float):Void;
  public function getColor():Array<Float>;
  public function setMaterial(material:Material):Void;
  public function getMaterial():Material;
  public function setFont(font:Font):Void;
  public function getFont():Font;
  public function setShader(shader:Shader):Void;
  public function getShader():Shader;
  public function setDepthTest(compareMode:String, write:Bool):Void;
  public function getDepthTest():Dynamic;
  public function setBlendMode(blend:String, ?alphaBlend:String):Void;
  public function getBlendMode():Dynamic;
  public function setWireframe(wireframe:Bool):Void;
  public function isWireframe():Bool;
  public function setWinding(winding:String):Void;
  public function getWinding():String;
  public function setColorMask(r:Bool, g:Bool, b:Bool, a:Bool):Void;
  public function getColorMask():Dynamic;
  public function setAlphaSampling(enabled:Bool):Void;
  public function getAlphaSampling():Bool;
  public function setLineWidth(width:Float):Void;
  public function getLineWidth():Float;
  public function setPointSize(size:Float):Void;
  public function getPointSize():Float;
  public function setCanvas(canvas:Dynamic):Void;
  public function setProjection(view:Int, matrix:Array<Float>):Void;
  public function setViewPose(index:Int, matrix:Array<Float>):Void;
  public function flush():Void;
  public function tick(label:String):Void;
  public function tock(label:String):Float;
  public function getViewAngles(view:Int):Dynamic;
  public function text(text:String, x:Float, y:Float, z:Float, scale:Float, ?angle:Float, ?ax:Float, ?ay:Float, ?az:Float):Void;
}